name: publish-to-pages
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'log level'
        required: true
        default: 'warning'
      tags:
        description: 'tag'
    push:
        branches:
            - main

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Cache Dependencies
              id: cache_deps
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: node-modules-${{ hashFiles('bun.lock') }}

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2

            - name: Install Dependencies
              shell: bash
              if: steps.cache_deps.outputs.cache-hit != 'true'
              run: bun install

            - name: Setup Pages
              uses: actions/configure-pages@v4
              with:
                  static_site_generator: true

            - name: Build Page
              run: bun run build

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: ./out

    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Publish to Pages
              id: deployment
              uses: actions/deploy-pages@v4
